# .rubocop.yml
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false
